<?
/**
 * Implements hook_form_alter().
 * 
 * @see wordpress_password_check_login() for new validator.
 */
function wordpress_password_form_user_login_alter(&$form,$form_state){
	if($form_id == 'user_login' || $form_id == 'user_login_block'){
		if(!is_array($form['#validate'])){
			$form['#validate'] = array($form['#validate']);
		}
		$form['#validate'][] = 'wordpress_password_check_login';
	}
}

/**
 * Validate function, loosely based on forgotten_login module.
 */
function wordpress_password_check_login($form,&$form_state){
	global $user;
	if($user->uid == 0){
		$uid = db_query('select u.uid from {users} u where u.status <> 0 and u.name = :name', array(':name' => $form_state['values']['name']))->fetchField();
		if($uid == false){
			return;
		}else{
			$user_data = unserialize(db_query('select u.data from {users} u where u.status <> 0 and u.name = :name', array(':name' => $form_state['values']['name']))->fetchField());
			if($user_data['wp_pass'] != 'ACTIVATED'){
				require($_SERVER['DOCUMENT_ROOT'].'/blog/wp-includes/class-phpass.php');
				$wp_hasher = new PasswordHash(8,true);
				if($wp_hasher->CheckPassword($form_state['values']['pass'],$user_data['wp_hash'])){
					if($user_data['wp_pass'] == $pw_hash){
						if($user_data['wp_pass'] != 'ACTIVATED'){
							$user_data['wp_pass'] = 'ACTIVATED';
							$new_pw_hash = user_hash_password($form_state['values']['pass']);
							$success = db_query('update users set pass = :new_pw_hash, data = :user_data where name = :name', array(
								':name' => $form_state['values']['name'],
								':new_pw_hash' => $new_pw_hash,
								':user_data' => mysql_real_escape_string(serialize($user_data))));
							if($success){
								$user->uid = $uid;
							}
						}
					}
				}
			}else{
				return;
			}
		}
	}
}